[project]
name = "voice-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "livekit>=1.1.8",
    "livekit-agents[deepgram,noise-cancellation,openai,silero,turn-detector]>=1.5.12",
    "python-dotenv>=1.2.2",
    "streamlit>=1.57.0",
    "torch>=2.12.0",
    "torchaudio>=2.11.0",
]
